### ISSUE TITLE
PowerMock disables EclEmma code coverage

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#422]
_From [linmingr...@gmail.com](https://code.google.com/u/112682308495640684339/) on September 10, 2012 09:55:56_

What steps will reproduce the problem? 1.Create a powermock test with Mockito, the test class is decorated with @RunWith and @PrepareForTest annotation.
2.Run the Test with "coverage as". What is the expected output? What do you see instead? Expected: EclEmma shows correct code coverage report.
Instead: EclEmma shows zero code coverage on target class. What version of the product are you using? On what operating system? 1. Eclipse is 3.7. 
1. EclEmma Plugin: 2.1.4. 
2. PowerMock: powermock-mockito-1.4.12-full.jar.
3. OS: Windows XP sp2. 
4. JDK: 1.6. Please provide any additional information below. N/A.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=402_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 12, 2012 03:58:28_

Could someone try if you get the same result if you test with the very latest (unreleased) Javassist?

**Comment by johanhaleby** [comment]
_From [mahnk...@gmail.com](https://code.google.com/u/116755112430534124319/) on October 16, 2012 03:52:52_

We are using latest unreleased Javassist and can confirm that the coverage report shows zero code coverage when using powermock tests with Mockito as reported in the original post.

**Comment by johanhaleby** [comment]
_From [ccha...@gmail.com](https://code.google.com/u/114108435735176297263/) on October 16, 2012 13:05:13_

I have the same issue:

EclEmma 2.1.4.201208011137
Eclipse 4.2
OpenJDK 7
ArchLinux 3.6.2-1 i686
powermock-api-mockito 1.4.12

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 16, 2012 23:01:00_

Did this occur with a new version of EclEmma or how come it has not been reported before?

**Comment by johanhaleby** [comment]
_From [mahnk...@gmail.com](https://code.google.com/u/116755112430534124319/) on October 17, 2012 00:06:15_

In our case we started to use powermock in order to be able to mock static methods and since then code coverage reports are incorrectly showing zero code coverage for the class we are testing using powermock.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 17, 2012 00:13:02_

Alright. I know cobertura had the same issue before but then it was an issue on their side this they fixed it a later version. Perhaps you can bring this up to Emma as well?

**Comment by johanhaleby** [comment]
_From [gabor.li...@gmail.com](https://code.google.com/u/117570574002796472922/) on October 17, 2012 00:17:10_

https://github.com/jacoco/eclemma/issues/15

**Comment by johanhaleby** [comment]
_From [gabor.li...@gmail.com](https://code.google.com/u/117570574002796472922/) on October 17, 2012 00:18:34_

If someone would have time to provide a test and a dummy class attached to this class, that would be useful for both parties.

**Comment by johanhaleby** [comment]
_From [mahnk...@gmail.com](https://code.google.com/u/116755112430534124319/) on October 17, 2012 02:27:43_

Please find attached a sample dummy project demonstrating the reported issue.

When running code coverage for unit test "TestClassUsingMockedStaticMethod.java", it shows zero % coverage in src/main/java

When running code coverage for unit test "TestClassUsingRealStaticMethod.java", it shows correct coverage % in src/main/java

**Attachment:** [issue402-example.zip](http://code.google.com/p/powermock/issues/detail?id=402#hc9)

**Comment by johanhaleby** [comment]
_From [gabor.li...@gmail.com](https://code.google.com/u/117570574002796472922/) on October 17, 2012 02:32:12_

Thanks for the sample classes.

**Comment by johanhaleby** [comment]
_From [zalava...@gmail.com](https://code.google.com/u/102415192670633938099/) on October 17, 2012 13:59:35_

This problem began with EclEmma 2.0.0, where they started using Jacoco.
With EclEmma 1.5.3 there is no such problem.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 17, 2012 21:41:25_

Then I suspect that problem must be fixed in Jacoco or Emma?

**Comment by johanhaleby** [comment]
_From [zalava...@gmail.com](https://code.google.com/u/102415192670633938099/) on October 17, 2012 22:46:25_

Yes, maybe. But they won't fix it: http://sourceforge.net/projects/eclemma/forums/forum/614869/topic/4803215

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 17, 2012 22:52:53_

Ok so there it says that "JaCoCo uses a hashcode of the class definition for class identity" so that's probably the reason why it won't work. PowerMock cannot work with modifying classes so I guess there's nothing that can be done in PowerMock to prevent this.. (correct me if I'm wrong).

**Comment by johanhaleby** [comment]
_From [zalava...@gmail.com](https://code.google.com/u/102415192670633938099/) on October 17, 2012 22:55:46_

The root of the problem: "JaCoCo uses a hashcode of the class definition for class identity."
So the cglib modified classes has different hashcodes than the originals.
I don't think the PowerMock guys can solve this problem, so I think this will be a long-term problem.

**Comment by johanhaleby** [comment]
_From [zalava...@gmail.com](https://code.google.com/u/102415192670633938099/) on October 17, 2012 22:56:10_

:)

**Comment by johanhaleby** [comment]
_From [gabor.li...@gmail.com](https://code.google.com/u/117570574002796472922/) on October 18, 2012 06:01:21_

I have just installed ecobertura. Works perfectly together with eclemma inside one eclipse. It is less handy as eclemma, but it delivers correct coverage. If you drag this link on eclipse, you can install that easily: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=1179

**Comment by johanhaleby** [comment]
_From [zalava...@gmail.com](https://code.google.com/u/102415192670633938099/) on November 19, 2012 01:37:51_

Yes, Cobertura is okay but it is not maintained anymore. (It hasn't got any update since 2011 june, so this is not a long term solution I think)

At the company we using Sonar, it has Cobertura and Jacoco plugins as well, but the supported way in sonar is also Jacoco for sime time.

**Comment by johanhaleby** [comment]
_From [headcrashing](https://code.google.com/u/headcrashing/) on February 22, 2013 10:45:39_

Seems to be related to `#432`.

**Comment by johanhaleby** [comment]
_From [giovanim...@gmail.com](https://code.google.com/u/102911500463228980706/) on April 10, 2013 07:35:06_

There forecasting correction?

**Comment by johanhaleby** [comment]
_From [eric...@gmail.com](https://code.google.com/u/105343280717079423150/) on April 14, 2013 16:25:39_

We use EasyMock with PowerMock and got similar issue. The only difference is that we always got 100% coverage of the under test class, even though there are lines not covered.

**Comment by johanhaleby** [comment]
_From [hghazo...@gmail.com](https://code.google.com/u/114524282427633537612/) on June 26, 2013 15:21:00_

I just tried using Clover with Powermock and it works. Not free but at least it works.

**Comment by johanhaleby** [comment]
_From [dakbhav...@gmail.com](https://code.google.com/u/112366601324219721911/) on May 25, 2015 06:18:00_

Facing the same issue. EclEmma giving zero code coverage with powermock based unit test.

**Comment by psmarcos** [comment]
Facing the same issue

**Comment by aijanai** [comment]
Same issue

**Comment by amitwave** [comment]
Can somebody suggest any solution?

**Comment by johanhaleby** [comment]
Are you using TestNG or JUnit?

**Comment by aijanai** [comment]
JUnit

**Comment by amitwave** [comment]
I am using jacoco plugin but the classes with powermocked test are not showing code coverage at all. Can someone please suggest a way or alternative which works.

**Comment by aijanai** [comment]
The latest version of Powermock works with JaCoCo.

But, after some other issues related to Powermock, I've resolved in surrounding static classes with factories and wrappes, so that I had to test instances only.

**Comment by amitwave** [comment]
I used the latest version of powermock and mockito which resolved the issue.

**Comment by PrabakaranSK** [comment]
@amitwave  - Could you explain what versions you have downloaded, also about the Eclipse and EclEmma versions?

**Comment by amarjain07** [comment]
I am using latest version of PowerMockito (1.6.4) as a gradle dependency in my android project and JaCoCo for Code coverage. I have written a test class for one of my utility classes with @Runwith PowerMockRunner and @PrepareForTest annotations. Everytime JaCoCo shows zero code coverage. 
Can someone here help me with this?

**Comment by MrBigDog2U** [comment]
I am still experiencing zero code coverage for PowerMock tested classes. Using
- PowerMock 1.6.4
- Mockito 1.10.19
- EclEmma 2.3.3
- Eclipse 4.5.2

**Comment by sapirgolan** [comment]
If JaCoCo does present some code coverage for you please specify the following:

- PowerMock version
- Mockito version (if using)
- JaCoCo version, either as eclipse plugin or maven plugin

**Comment by ralphavalon** [comment]
Solved here.

* PowerMock: 1.6.5
* EclEmma: 2.3.3
* Eclipse Luna: 4.4.0

I just updated the EclEmma plugin (Help > Install New Software > EclEmma > Update...) and it works now.

**Comment by tenwx** [comment]
import maven dependency:
<dependency>
	<groupId>org.powermock</groupId>
	<artifactId>powermock-module-junit4-rule-agent</artifactId>
	<version>${powermock.version}</version>
	<scope>test</scope>
</dependency>

use :
@Rule
public PowerMockRule rule = new PowerMockRule();
instead of:
@RunWith(PowerMockRunner.class)

then it works! Amazing!

**Comment by alan125** [comment]
@tenwx, the problem with using PowerMockRule with the java agent is that it disables debugging in the IDE

**Comment by stewie11** [comment]
@tenwx 你有联系方式吗,我想问问关于这个问题刚好这两天用到了powermock,不能使用了

**Comment by tenwx** [comment]
@alan125 It's true. But every coin has two sides. :)

**Comment by tenwx** [comment]
@stewie11 What's your problem? Does use PowerMockRule not work?

**Comment by stewie11** [comment]
@tenwx  
I'm not sure how to replace "@RunWith..." annotation without affect powermock's behavior.

cuz I'm using ”org.powermock.api.mockito.PowerMockito.mockStatic“ to mock a static-method which is a static method of the "Utility" class

To be more specific...
...
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PowerMockIgnore("javax.management.*")
public class XXXTest { 
	...
	@Test
	@PrepareForTest(Utility.class)
	public void unit1Test() {
		org.powermock.api.mockito.PowerMockito.mockStatic(Utility.class);
		org.powermock.api.mockito.PowerMockito.when(Utility.staticMethod()).thenReturn(0);
	}
}

After I did what you told, EclEmma works fine, Now without the "RunWith" annotation PowerMockito.when would throw an exception What to do to deal with this scenario  ?

@PowerMockIgnore("javax.management.*")
public class XXXTest {
	@Rule
	public PowerMockRule rule = new PowerMockRule();
	....
	@Test
	@PrepareForTest(Utility.class)
	public void unit1Test() {
		...
		org.powermock.api.mockito.PowerMockito.mockStatic(Utility.class);
		org.powermock.api.mockito.PowerMockito.when(Utility.staticMethod()).thenReturn(0);
	}
}

**Comment by tenwx** [comment]
@stewie11 Because of your mistake usage on PrepareForTest annotation. You should try this:
@PrepareForTest({Utility.class})
It's an array.

**Comment by alan125** [comment]
@tenwx PrepareForTest can take both an array or a single class. The usage mentioned is not wrong

@stewie11 make sure that you are eagerly loading PowerMock's Java Agent. For example, your JVM arguments should have something like this `[PATH_TO_YOUR_M2_REPO]/org/powermock/powermock-module-javaagent/1.6.5/powermock-module-javaagent-1.6.5.jar`. Also I never tried PrepareForTest on the test method, but rather on the whole class.

Finally, using PowerMockRule has some limitations, like being unable to change internal state of final static variables, and disabling static initialization. It also caused some weird behaviors in some of my tests. After all, this is still an experimental feature.

**Comment by fmaillane** [comment]
I downgraded the EclEmma version to 1.5.3 and works fine now, is the only solution that i can found for now...

**Comment by github-karen** [comment]
Hi, @ralphavalon ! Could you tell me what's the java and junit version you are using? Thank you~ 
I have the same PowerMock, EclEmma and Eclipse version with yours, but I still get the 0% coverage if I put the @PrepareForTest(ClassUnderTest.class) at the junit class-level.

**Comment by ralphavalon** [comment]
Hi @github-karen, I'm using:

Java 1.7
JUnit 4.12

**Comment by github-karen** [comment]
@ralphavalon Thank you for your reply~ It seems the difference is with our Java version. I'm still having the issue with using PowerMock with EclEmma. But I found another Eclipse coverage plugin CLOVER which works good with PowerMock. What's NOT that good is that it needs license to use it after 29 trial days.

**Comment by Rafael-Simonelli** [comment]
I'm having this issue right now. But specifically when mocking the private methods of the class under tests. Just using PowerMock's runner performs correctly the code coverage.

Java 1.8
Easymock 3.4
Powermock 1.6.5
JUnit 4.12
JaCoCO 0.7.6.201602180812
EclEmma Plugin 2.3.3.201602231923

The issue occurs with either the EclEmma plugin from Eclipse or JaCoCo... Is there any "workaround" or known solution until the issue is fixed?

**Comment by KumrN** [comment]
I picked the PowerMockito version 1.6.4 and Mockito version 1.10.19 using Java 1.8
and I ran my test cases having Powermockito.mockStatic() using EclEmma plugin and could see the correct coverage. where as test cases using PowerMockito.spy(), its giving zero coverage.

**Comment by kirandongare** [comment]
Hi Guys,

I'm facing problem with PowerMockito.mockStatic() when I have added Jacoco code coverage. Is there any solution for Jacoco to run mockStatic with PowerMockito.

Please reply back.

**Comment by thekingnothing** [comment]
Fixed by ignoring all synthetic methods/fields, as it was recommended by Jacoco team.

**Comment by saurabhkala** [comment]
EclEmma 	2.3.3.201602231923	
Eclipse Neon.1a Release (4.6.1)
Java 8
Powermock 1.6.6 (built the artifact using main github branch)
I still do not see any coverage with EclEmma plugin when using "spy".

**Comment by thekingnothing** [comment]
Sorry, when I closed the issue, I missed one point that it's an eclipse plug-in and it uses JaCoCo Agent. But PowerMock can work only with JaCoCo offline instrumented classes. 

But unfortunately, theres no way to fix the issue right now (more information you may fin here https://github.com/jacoco/jacoco/issues/51), so I keep the issue closed, but with different status: "cannot be fixed"

**Comment by KumrN** [comment]
As per release notes of PowerMockito 1.6.6, It's indicating that the issue#422 has been fixed with 1.6.6.
Isn't the case ? Is there any alternate way to get the coverage using maven jacoco plugin instead of eclipse plugin ? I appreciate your reply. Thanks.

**Comment by alan125** [comment]
Just tested with maven, and issue is still there
[test.zip](https://github.com/jayway/powermock/files/581469/test.zip)

**Comment by thekingnothing** [comment]
@KumrN, I apologize for the inconvenience. It was added in realise notes by mistake. It had to be closed as "cannot be fixed". 
You can use [JaCoCo Offline Instrumentation](http://www.eclemma.org/jacoco/trunk/doc/offline.html) and maven plugin to collect code coverage. Working example JaCoCo + PowerMock you may find [here](https://github.com/thekingnothing/powermock-jacoco/tree/master/offline)

**Comment by thekingnothing** [comment]
@alan125, as I mentioned in my answers above, PowerMock can work only with JaCoCo Offline instrumentation. PowerMock uses custom class loader and reads class from disk, so all agents changes are invisible for PowerMock.  In your example you're using JaCoCo agent

**Comment by natrajayappan** [comment]
Hi All, 
        I am still facing issues with the following.
JDK 1.8
Eclipse Neon 4.6.2
Ecl Emma 2.3.3
Powermock 1.6.5

Can someone help me here?

**Comment by albfan** [comment]
Seems useful to link to this workaround http://www.notonlyanecmplace.com/make-eclemma-test-coverage-work-with-powermock/

**Comment by tushargoyal22** [comment]
> Seems useful to link to this workaround http://www.notonlyanecmplace.com/make-eclemma-test-coverage-work-with-powermock/

Link is not accessible, can someone share what is the workaround..

**Comment by albfan** [comment]
Link is accesible
